### ISSUE TITLE
Rest API for Builder 

### ISSUE THREAD

**Issue by omarkhatibco** [TypeRocket/plugin-builder#1]
Hi, 

I'm testing typeRocket for a headless project & I was wondering, is there any way I can expose builder data to Rest API ? 

if there isn't, is there any php function, can I use to retrive the data for the builder as array ?

Best Regards 
Omar

**Comment by kevindees** [comment]
Hey @omarkhatibco 

You can. The builder data is apart of the meta so you just need to expose the post meta to your API using eager loading.

https://typerocket.com/docs/v4/models/#section-with-eager-loading

Thanks,
Kevin

**Comment by omarkhatibco** [comment]
Hi @kevindees,
Thanks for you.
